server:
  port: 9011

spring:
  datasource:
    url: jdbc:mysql://192.168.0.160:3306/wangwei_control?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: wangwei
    password: wangwei123

  redis:
    database: 0
    password:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    root: info
  path: /home/dsftp/application/control/
