server:
  port: 9011

spring:
  datasource:
    url: jdbc:mysql://182.161.66.18:3306/risk_control?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: risk_control
    password: risk_control

  redis:
    database: 0
    password: Xs@Linyd@iM
    host: 172.17.0.1
    port: 6379

logger:
  level: info
  path: /home/xsyunwei/application/control/
